import {app,BrowserWindow,ipcMain} from 'electron';import {join,dirname} from 'path';import {fileURLToPath} from 'url';import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'fs';import {registerFloatWindowIpc,createFloatWindow,destroyFloatWindow,hideFloatWindow} from './floatWindow'
const __filename=fileURLToPath(import.meta.url)
const __dirname=dirname(__filename)
let mw:BrowserWindow|null=null
let dbPath=''
function db(){if(!dbPath){const d=join(app.getPath('userData'),'data');if(!existsSync(d))mkdirSync(d,{recursive:true});dbPath=join(d,'flights.json')}return dbPath}
function readFlights():any[]{try{if(existsSync(db()))return JSON.parse(readFileSync(db(),'utf-8'))}catch(e){}return[]}
function writeFlights(data:any[]){try{writeFileSync(db(),JSON.stringify(data),'utf-8')}catch(e){}}
function createWindow(){mw=new BrowserWindow({width:1200,height:800,minWidth:900,minHeight:600,title:'Interstellar-Flight',frame:true,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:false,preload:join(__dirname,'preload.js')},show:true,backgroundColor:'#0f172a'});mw.on('minimize',async()=>{try{const s=await mw?.webContents.executeJavaScript('window.__flightState||null');if(s&&s.isFlying)createFloatWindow()}catch{createFloatWindow()}});mw.on('restore',()=>hideFloatWindow());if(process.env.VITE_DEV_SERVER_URL)mw.loadURL(process.env.VITE_DEV_SERVER_URL);else mw.loadFile(join(__dirname,'../dist/index.html'))}
function registerIpc(){ipcMain.on('window:minimize',()=>mw?.minimize());ipcMain.on('window:maximize',()=>mw?.isMaximized()?mw.unmaximize():mw?.maximize());ipcMain.on('window:close',()=>mw?.close());ipcMain.on('window:restoreMain',()=>{mw?.restore();mw?.focus();hideFloatWindow()});ipcMain.handle('getFlightState',async()=>{if(!mw||mw.isDestroyed())return null;try{const s=await mw.webContents.executeJavaScript('window.__flightState||null');if(!s)return null;if(!s.isFlying)return{isFlying:false};return s}catch{return null}});ipcMain.handle('db:saveFlight',async(_,d:any)=>{try{const flights=readFlights();flights.unshift(d);writeFlights(flights);return true}catch{return false}});ipcMain.handle('db:getFlights',async(_,f:any)=>{try{let flights=readFlights();if(f?.limit)flights=flights.slice(0,f.limit);return flights}catch{return[]}});ipcMain.handle('db:getStats',async()=>{try{const flights=readFlights();const total=flights.length;if(total===0)return{total_mileage:0,total_flights:0,total_focus_minutes:0,current_streak:0,longest_streak:0,last_flight_date:null,rank_level:1,unlocked_routes:'[]',unlocked_aircrafts:'[]'};const totalMileage=flights.reduce((s:number,f:any)=>s+(f.mileageEarned||0),0);const totalFocus=flights.reduce((s:number,f:any)=>s+Math.round((f.actualDuration||0)/60),0);let streak=0,longest=0;const sorted=[...flights].sort((a,b)=>new Date(b.endedAt).getTime()-new Date(a.endedAt).getTime());for(let i=0;i<sorted.length;i++){if(sorted[i].status==='completed'){streak++;if(streak>longest)longest=streak}else break}return{total_mileage:totalMileage,total_flights:total,total_focus_minutes:totalFocus,current_streak:streak,longest_streak:longest,last_flight_date:sorted[0]?.endedAt||null,rank_level:1,unlocked_routes:'[]',unlocked_aircrafts:'[]'}}catch{return{total_mileage:0,total_flights:0,total_focus_minutes:0,current_streak:0,longest_streak:0,last_flight_date:null,rank_level:1,unlocked_routes:'[]',unlocked_aircrafts:'[]'}}});ipcMain.on('flight:start',(_,d:any)=>{d.startedAt=Date.now()});ipcMain.on('flight:clear',()=>{});ipcMain.on('flight:completeFromFloat',async()=>{if(!mw||mw.isDestroyed())return;try{await mw.webContents.executeJavaScript('if(window.__completeFlight)window.__completeFlight()')}catch{}})}
app.whenReady().then(()=>{registerIpc();registerFloatWindowIpc();createWindow()});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})
