export interface GalaxyConfig{id:string;name:string;nameZh:string;center:[number,number,number];starColor:string;glowColor:string;nebulaColor:string;starSize:number;shape:'spiral'|'elliptical'|'irregular'|'ring'|'barred'|'twin'|'sparse';shapeParams:Record<string,number>}
export const GALAXIES:GalaxyConfig[]=[
{id:'dawnspire',name:'Dawnspire',nameZh:'晨曦群岛',center:[14,2,10],starColor:'#ffd700',glowColor:'#ffaa00',nebulaColor:'#664400',starSize:0.22,shape:'spiral',shapeParams:{arms:2,turns:2.5,spread:2.0,armWidth:0.6}},
{id:'frostridge',name:'Frostridge',nameZh:'霜脊高原',center:[0,11,-5],starColor:'#b8e0f8',glowColor:'#88ccff',nebulaColor:'#112244',starSize:0.2,shape:'elliptical',shapeParams:{rx:2.8,ry:1.2,rz:0.9,tilt:0.4}},
{id:'crucible',name:'Crucible',nameZh:'熔炉盆地',center:[-11,-1,8],starColor:'#ff6622',glowColor:'#ff4400',nebulaColor:'#441100',starSize:0.21,shape:'irregular',shapeParams:{spread:2.2,clusters:3,chaos:1.5}},
{id:'verdant',name:'Verdant',nameZh:'翡翠深渊',center:[10,0,13],starColor:'#4ade80',glowColor:'#22c55e',nebulaColor:'#003310',starSize:0.2,shape:'ring',shapeParams:{radius:2.0,thickness:0.4,height:0.6}},
{id:'silversand',name:'Silversand',nameZh:'银沙海域',center:[2,0,15],starColor:'#f0dcc0',glowColor:'#e8c878',nebulaColor:'#332200',starSize:0.19,shape:'barred',shapeParams:{barLength:3.0,barWidth:0.4,armSpread:1.2}},
{id:'stormveil',name:'Stormveil',nameZh:'风暴环带',center:[3,8,2],starColor:'#b0bcc8',glowColor:'#c8d0e0',nebulaColor:'#1a1a2a',starSize:0.19,shape:'twin',shapeParams:{separation:1.8,clusterRadius:0.9}},
{id:'starfall',name:'Starfall',nameZh:'星落深域',center:[-13,5,-8],starColor:'#c4a8f8',glowColor:'#8b5cf6',nebulaColor:'#1a0840',starSize:0.21,shape:'sparse',shapeParams:{spread:3.0,density:0.5,voidRadius:0.8}},
]
export interface StarPosition{x:number;y:number;z:number}
function seedRand(seed:string):()=>number{let h=0;for(let i=0;i<seed.length;i++)h=((h<<5)-h+seed.charCodeAt(i))|0;return()=>{h=(h*1103515245+12345)|0;return(h>>>0)/0xffffffff}}
function genPositions(g:GalaxyConfig,ids:string[]):Record<string,StarPosition>{const[cx,cy,cz]=g.center;const p=g.shapeParams;const res:Record<string,StarPosition>={};ids.forEach((id,idx)=>{const r=seedRand(id+g.id);let x=0,y=0,z=0;switch(g.shape){case'spiral':{const arm=idx%p.arms,armA=(arm/p.arms)*Math.PI*2,t=(idx/ids.length)*p.turns*Math.PI+r()*0.4,rad=t/(p.turns*Math.PI)*p.spread,scat=r()*p.armWidth;x=cx+Math.cos(armA+t)*(rad+scat);z=cz+Math.sin(armA+t)*(rad+scat);y=cy+(r()-0.5)*p.armWidth*1.5;break}case'elliptical':{const rx=p.rx*(0.1+r()*0.9),rz=p.rz*(0.1+r()*0.9),ry=p.ry*(0.1+r()*0.9);x=cx+rx*(r()>0.5?1:-1);z=cz+rz*(r()>0.5?1:-1);y=cy+(r()-0.5)*ry*2;break}case'irregular':{const ci=Math.floor(r()*p.clusters),ca=(ci/p.clusters)*Math.PI*2+r()*0.8,cd=p.spread*(0.15+r()*0.85),sc=p.spread*0.4*(0.3+r()*0.7);x=cx+Math.cos(ca)*cd+(r()-0.5)*sc*2;z=cz+Math.sin(ca)*cd+(r()-0.5)*sc*2;y=cy+(r()-0.5)*p.spread*p.chaos;break}case'ring':{const a=(idx/ids.length)*Math.PI*2+(r()-0.5)*0.5,rad=p.radius+(r()-0.5)*p.thickness*2;x=cx+Math.cos(a)*rad;z=cz+Math.sin(a)*rad;y=cy+(r()-0.5)*p.height*2;break}case'barred':{if(idx<ids.length*0.35){x=cx+(r()-0.5)*p.barLength;z=cz+(r()-0.5)*p.barWidth;y=cy+(r()-0.5)*0.3}else{const s=idx%2===0?1:-1,a=Math.PI*0.4*s+r()*1.0,rad=p.barLength*0.4+r()*p.armSpread;x=cx+Math.cos(a)*rad;z=cz+Math.sin(a)*rad;y=cy+(r()-0.5)*0.8}break}case'twin':{const ci=idx<ids.length/2?0:1,d=ci===0?-1:1,cr=p.clusterRadius*(0.1+r()*0.9),ca=r()*Math.PI*2;x=cx+d*p.separation*0.5+Math.cos(ca)*cr;z=cz+Math.sin(ca)*cr;y=cy+(r()-0.5)*cr*1.5;break}case'sparse':{const a=r()*Math.PI*2,rad=p.voidRadius*0.3+r()*p.spread;x=cx+Math.cos(a)*rad;z=cz+Math.sin(a)*rad;y=cy+(r()-0.5)*p.spread*0.8;break}}res[id]={x,y,z}});return res}
const galaxyCities:Record<string,string[]>={dawnspire:['lumhaven','cascadel','coralis','bellrise','mistlotus','goldwing','irisford','dewpoint'],frostridge:['glaciara','aurorath','belugard','frostforge','owlcrest','stillmere','northpoint','crevassgate'],crucible:['pyrathis','anvilsoul','slagflow','cinderport','cogsworth','brimhollow','embercrest','obsidara'],verdant:['canopolis','vinearch','glowvale','pollenport','rootvein','nesthollow','terradew','sporelume'],silversand:['mirageth','halithar','solarcrown','duneport','glyphara','oasguard','stardustcove','erogate'],stormveil:['thunderseat','boltanchor','vortexia','calmhaven','nimbuforge','galecrest','aegistorm'],starfall:['meteoris','darkstella','voidmere','cometail','crystalfield','echospire','riftsgate','finalglow']}
export const STAR_POSITIONS:Record<string,StarPosition>=(()=>{const all:Record<string,StarPosition>={};for(const[gid,ids]of Object.entries(galaxyCities))Object.assign(all,genPositions(GALAXIES.find(g=>g.id===gid)!,ids));all['aximund']={x:0,y:2,z:4.5};all['skymercia']={x:1.8,y:1.2,z:3.5};all['sentinelle']={x:-1.5,y:1.5,z:3};return all})()
export function getGalaxyForCity(cityId:string):GalaxyConfig|undefined{for(const[gid,ids]of Object.entries(galaxyCities))if(ids.includes(cityId))return GALAXIES.find(g=>g.id===gid);return undefined}
